### ISSUE TITLE
Do not retry on `ExpectationFailedException`

### ISSUE THREAD

**Issue by ava12** [bshaffer/phpunit-retry-annotations#7]
When a test makes an assertion and it fails, a `PHPUnit\Framework\ExpectationFailedException` is thrown. When it happens the test definitely should not be retried (it's just meaningless).

`RetryTrait` currently filters out (i. e. rethrows) `IncompleteTestError` and `SkippedTestError`. I think it should also filter out `ExpectationFailedException`.

**Comment by bshaffer** [comment]
Thank you @ava12 !
In my use-cases, which are often flakey integration tests, if the phpunit assertion fails I determine that particular run to be flakey, and so re-run the tests. The assertion _should_ pass, so if it fails, I want to make sure it's not flakey, so I run the test again.

In other words, retrying on `ExpectationFailedException` is _precisely_ how I expect this library to be used.

To change this as the default behavior, check out [Configuring Retry Conditions](https://github.com/bshaffer/phpunit-retry-annotations#configuring-retry-conditions) and either add a custom retry method, or define which Exceptions you **do** want to retry.
